# Generated by Django 4.2.9 on 2024-02-04 18:03

from django.db import migrations, models
import enumchoicefield.fields
import farm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earing_number', models.CharField(max_length=50)),
                ('sex', enumchoicefield.fields.EnumChoiceField(default=farm.models.Sex(1), enum_class=farm.models.Sex, max_length=6)),
                ('date_of_birth', models.DateField()),
                ('breed', models.CharField(max_length=50)),
                ('in_program', models.BooleanField()),
            ],
        ),
    ]
